# Generated by Django 3.1 on 2020-08-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0002_user_brands_user_lipsticks_user_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lipsticks',
        ),
    ]
