# Generated by Django 3.1 on 2020-08-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cosmetics', '0003_delete_lipsticks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipsticks',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=45)),
                ('id', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('color_gamut', models.CharField(max_length=4)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cosmetics.series')),
            ],
        ),
    ]
